set -a terminal-features "screen256color:RGB"
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g mouse on
set -g focus-events on
set -g history-limit 99999
set -g extended-keys on
set -g extended-keys-format csi-u

# Rose Pine colors
rose_pine_base="#191724"
rose_pine_surface="#1f1d2e"
rose_pine_overlay="#26233a"
rose_pine_muted="#6e6a86"
rose_pine_subtle="#908caa"
rose_pine_text="#e0def4"
rose_pine_love="#eb6f92"
rose_pine_gold="#f6c177"
rose_pine_rose="#ebbcba"
rose_pine_pine="#31748f"
rose_pine_foam="#9ccfd8"
rose_pine_iris="#c4a7e7"

# General UI
set -g status on
set -g status 2
set -g status-position top
set -g status-justify centre
set -g status-style "bg=#191724,fg=#e0def4"
set -g pane-border-style "fg=#26233a"
set -g pane-active-border-style "fg=#c4a7e7"

# Messages / prompts
set -g message-style "bg=#26233a,fg=#e0def4"
set -g message-command-style "bg=#26233a,fg=#f6c177"
set -g mode-style "bg=#31748f,fg=#191724,bold"

# Window titles
set -g window-status-format " #[fg=#908caa]#I #[fg=#6e6a86]#W "
set -g window-status-current-format "#[fg=#c4a7e7,bg=#191724]#[fg=#191724,bg=#c4a7e7,bold] #I:#W #[fg=#c4a7e7,bg=#191724]"
set -g window-status-current-style "fg=#c4a7e7,bold"

# Left / right status
set -g status-left-length 40
set -g status-left "#[fg=#ebbcba,bg=default]#[fg=#191724,bg=#ebbcba,bold] #S #[fg=#ebbcba,bg=#191724]"

set -g status-right-length 80
set -g status-right "#[fg=#26233a,bg=#191724]#[fg=#e0def4,bg=#26233a] %Y-%m-%d #[fg=#9ccfd8,bg=#26233a] %H:%M #[fg=#26233a,bg=#191724]"

# Activity
set -g window-status-activity-style "fg=#f6c177,bold"
set -g visual-activity off
set -g status-format[1] "#[bg=default] "


# Keybinds
bind r source-file "~/.config/tmux/tmux.conf" \; display-message "tmux.conf reloaded"
bind f display-popup -E -w 80% -h 80% "~/.config/tmux/tmux-session-dispensary.sh"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key t display-popup -E -w 80% -h 80% "$SHELL"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
