local vars = require("config.vars")
require("config.monitors")

require("config.env")
require("config.autostart")(vars)
require("config.appearance")
require("config.animations")
require("config.workspaces")
require("config.input")
require("config.binds")(vars)
require("config.rules")
require("config.workspace_hooks")
