splash = false
ipc = true
preload = /home/nuznhy/wallpaper/marinbw.png
preload = /home/nuznhy/wallpaper/hyprtv.jpg
preload = /home/nuznhy/wallpaper/marin.png
preload = /home/nuznhy/wallpaper/marin-rose-pine.png

wallpaper { 
   monitor = DP-1
   path = /home/nuznhy/wallpaper/marin-rose-pine.png 
   fit_mode = cover
}
wallpaper { 
   monitor = DP-2
   path = /home/nuznhy/wallpaper/marin-rose-pine.png 
   fit_mode = cover
}
wallpaper { 
   monitor = HDMI-A-1
   path = /home/nuznhy/wallpaper/marin-rose-pine.png 
   fit_mode = cover
}
